[package]
name = "portctl"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "portctl"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
reqwest = { version = "0.13.2", features = ["json"], default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
rand = "0.10.0"
