use std::{collections::HashMap, path::Path};

use crate::client::EnvVar;
use crate::credentials::Credentials;
use crate::error::Error;
use crate::utils::generate_password;

const AUTOGENERATED: &str = "$auto";
const HOST_IP_PLACEHOLDER: &str = "$host_ip";

#[derive(Debug, Clone, Default)]
pub struct GeneratedCredentials {
    pub user: Option<String>,
    pub password: Option<String>,
}

#[derive(Debug, Clone)]
pub struct ResolvedStack {
    pub name: String,
    pub template_name: String,
    pub compose_content: String,
    pub env_vars: Vec<EnvVar>,
    pub generated_credentials: GeneratedCredentials,
}

#[derive(Debug, Clone)]
pub struct ProxyDef {
    pub name: String,
    pub domain: String,
    pub scheme: String,
    pub forward_host: String,
    pub forward_port: u16,
    pub websockets: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum CredRole {
    User,
    Password,
    None,
}

#[derive(Debug, Clone, Copy)]
struct EnvDefault {
    key: &'static str,
    default: &'static str,
    /// Which credential field this key maps to (if any).
    cred_role: CredRole,
}

impl EnvDefault {
    const fn user(key: &'static str, default: &'static str) -> Self {
        Self {
            key,
            default,
            cred_role: CredRole::User,
        }
    }

    const fn password(key: &'static str, default: &'static str) -> Self {
        Self {
            key,
            default,
            cred_role: CredRole::Password,
        }
    }

    const fn plain(key: &'static str, default: &'static str) -> Self {
        Self {
            key,
            default,
            cred_role: CredRole::None,
        }
    }
}

#[derive(Debug, Clone, Copy)]
struct StaticProxyDef {
    name: &'static str,
    scheme: &'static str,
    forward_host: &'static str,
    forward_port: u16,
    websockets: bool,
}

#[derive(Debug, Clone)]
struct TemplateConfig {
    stack_name: &'static str,
    env_defaults: Vec<EnvDefault>,
    proxies: &'static [StaticProxyDef],
}

fn builtin_templates() -> HashMap<&'static str, TemplateConfig> {
    let mut m = HashMap::new();

    m.insert(
        "npm",
        TemplateConfig {
            stack_name: "nginx-proxy-manager",
            env_defaults: vec![
                EnvDefault::user("INITIAL_ADMIN_EMAIL", "admin@mail.com"),
                EnvDefault::password("INITIAL_ADMIN_PASSWORD", AUTOGENERATED),
            ],
            proxies: &[],
        },
    );

    m.insert(
        "wireguard",
        TemplateConfig {
            stack_name: "wireguard-vpn",
            env_defaults: vec![
                EnvDefault::user("WG_ADMIN_USER", "admin"),
                EnvDefault::password("WG_ADMIN_PASS", AUTOGENERATED),
                EnvDefault::plain("WG_HOST", HOST_IP_PLACEHOLDER),
                EnvDefault::plain("WG_PORT", "51820"),
            ],
            proxies: &[StaticProxyDef {
                name: "Wireguard VPN Admin",
                scheme: "http",
                forward_host: "wg-easy",
                forward_port: 51821,
                websockets: true,
            }],
        },
    );

    m
}

pub fn print_available_templates() {
    println!("Available built-in stack templates:");
    let mut names: Vec<_> = builtin_templates().into_keys().collect();
    names.sort();
    print!("{}", names.join(", "));
}

pub fn resolve_stack(
    host_ip: &str,
    template_name: &str,
    compose_content: String,
    overrides: &HashMap<String, String>,
    existing_creds: Option<&Credentials>,
) -> Result<ResolvedStack, Error> {
    let builtins = builtin_templates();
    let mut env: HashMap<String, String> = HashMap::new();
    let mut generated_credentials = GeneratedCredentials::default();

    if let Some(config) = builtins.get(template_name) {
        for entry in &config.env_defaults {
            let value =
                resolve_env_value(&entry, host_ip, existing_creds, &mut generated_credentials);
            env.insert(entry.key.to_string(), value);
        }
    }

    env.extend(overrides.iter().map(|(k, v)| (k.clone(), v.clone())));

    let stack_name = builtins
        .get(template_name)
        .map(|c| c.stack_name.to_string())
        .unwrap_or_else(|| template_name.to_string());

    Ok(ResolvedStack {
        name: stack_name,
        template_name: template_name.to_string(),
        compose_content,
        env_vars: env
            .into_iter()
            .map(|(name, value)| EnvVar { name, value })
            .collect(),
        generated_credentials,
    })
}

pub fn default_proxies_for_template(template_name: &str, host_ip: &str) -> Vec<ProxyDef> {
    builtin_templates()
        .get(template_name)
        .map(|config| {
            config
                .proxies
                .iter()
                .map(|p| ProxyDef {
                    name: p.name.to_string(),
                    domain: host_ip.to_string(),
                    scheme: p.scheme.to_string(),
                    forward_host: p.forward_host.to_string(),
                    forward_port: p.forward_port,
                    websockets: p.websockets,
                })
                .collect()
        })
        .unwrap_or_default()
}

fn resolve_env_value(
    entry: &EnvDefault,
    host_ip: &str,
    existing_creds: Option<&Credentials>,
    generated_credentials: &mut GeneratedCredentials,
) -> String {
    let value = match entry.default {
        AUTOGENERATED => {
            let reused = existing_creds.and_then(|c| match entry.cred_role {
                CredRole::User => c.user.clone(),
                CredRole::Password => c.password.clone(),
                CredRole::None => None,
            });
            reused.unwrap_or_else(|| generate_password(20))
        }
        HOST_IP_PLACEHOLDER => host_ip.to_string(),
        other => other.to_string(),
    };

    // Record the value in generated_credentials for the appropriate role.
    match entry.cred_role {
        CredRole::User => generated_credentials.user = Some(value.clone()),
        CredRole::Password => generated_credentials.password = Some(value.clone()),
        CredRole::None => {}
    }

    value
}
